options:
  custom-slurm-repo:
    type: string
    default: ""
    description: >
      Use a custom repository for Slurm installation.

      This can be set to the Organization's local mirror/cache of packages and
      supersedes the Omnivector repositories. Alternatively, it can be used to
      track a `testing` Slurm version, e.g. by setting to
      `ppa:omnivector/osd-testing` (on Ubuntu), or
      `https://omnivector-solutions.github.io/repo/centos7/stable/$basearch`
      (on CentOS).

      Note: The configuration `custom-slurm-repo` must be set *before*
      deploying the units. Changing this value after deploying the units will
      not reinstall Slurm.
  cluster-name:
    type: string
    default: osd-cluster
    description: >
      Name to be recorded in database for jobs from this cluster.

      This is important if a single database is used to record information from
      multiple Slurm-managed clusters.
  default-partition:
    type: string
    default: ""
    description: >
      Default Slurm partition. This is only used if defined, and must match an
      existing partition.
  custom-config:
    type: string
    default: ""
    description: >
      User supplied Slurm configuration.

      This value supplements the charm supplied `slurm.conf` that is used for
      Slurm Controller and Compute nodes.

      Example usage:
      $ juju config slurmcltd custom-config="FirstJobId=1234"
  proctrack-type:
    type: string
    default: proctrack/cgroup
    description: >
      Identifies the plugin to be used for process tracking on a job step
      basis.
  cgroup-config:
    type: string
    default: |
      CgroupAutomount=yes
      ConstrainCores=yes
    description: >
      Configuration content for `cgroup.conf`.

  health-check-params:
    default: ""
    type: string
    description: >
      Extra parameters for NHC command.

      This option can be used to customize how NHC is called, e.g. to send an
      e-mail to an admin when NHC detects an error set this value to
      `-M admin@domain.com`.
  health-check-interval:
    default: 600
    type: int
    description: Interval in seconds between executions of the Health Check.
  health-check-state:
    default: "ANY,CYCLE"
    type: string
    description: Only run the Health Check on nodes in this state.

  acct-gather-frequency:
    type: string
    default: "task=30"
    description: >
      Accounting and profiling sampling intervals for the acct_gather plugins.

      Note: A value of `0` disables the periodic sampling. In this case, the
      accounting information is collected when the job terminates.

      Example usage:
      $ juju config slurmcltd acct-gather-frequency="task=30,network=30"
  acct-gather-custom:
    type: string
    default: ""
    description: >
      User supplied `acct_gather.conf` configuration.

      This value supplements the charm supplied `acct_gather.conf` file that is
      used for configuring the acct_gather plugins.
